### ISSUE TITLE
Failed to load models

### ISSUE THREAD

**Issue by PGCRT** [if-ai/ComfyUI-IF_MemoAvatar#1]
Failed to load models: Unable to load weights from checkpoint file for 'D:\SD\ComfyUI_windows_portable\ComfyUI\models\checkpoints\memo\diffusion_net\diffusion_pytorch_model.safetensors' at 'D:\SD\ComfyUI_windows_portable\ComfyUI\models\checkpoints\memo\diffusion_net\diffusion_pytorch_model.safetensors'.

<details>
  <summary>Log</summary>
  
got prompt
Loading models
The config attributes {'center_input_sample': False, 'out_channels': 4} were passed to UNet2DConditionModel, but are not expected and will be ignored. Please verify your config.json configuration file.
The config attributes {'addition_embed_type': None, 'addition_embed_type_num_heads': 64, 'addition_time_embed_dim': None, 'attention_type': 'default', 'center_input_sample': False, 'class_embeddings_concat': False, 'conv_in_kernel': 3, 'dropout': 0.0, 'encoder_hid_dim': None, 'encoder_hid_dim_type': None, 'mid_block_only_cross_attention': None, 'num_attention_heads': None, 'projection_class_embeddings_input_dim': None, 'reverse_transformer_layers_per_block': None, 'time_cond_proj_dim': None, 'time_embedding_act_fn': None, 'time_embedding_dim': None, 'time_embedding_type': 'positional', 'timestep_post_act': None, 'transformer_layers_per_block': 1} were passed to UNet3DConditionModel, but are not expected and will be ignored. Please verify your config.json configuration file.
Error loading models: Unable to load weights from checkpoint file for 'D:\SD\ComfyUI_windows_portable\ComfyUI\models\checkpoints\memo\diffusion_net\diffusion_pytorch_model.safetensors' at 'D:\SD\ComfyUI_windows_portable\ComfyUI\models\checkpoints\memo\diffusion_net\diffusion_pytorch_model.safetensors'.
Traceback (most recent call last):
  File "D:\SD\ComfyUI_windows_portable\python_embeded\Lib\site-packages\diffusers\models\model_loading_utils.py", line 142, in load_state_dict
    return safetensors.torch.load_file(checkpoint_file, device="cpu")
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\SD\ComfyUI_windows_portable\python_embeded\Lib\site-packages\safetensors\torch.py", line 313, in load_file
    with safe_open(filename, framework="pt", device=device) as f:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
safetensors_rust.SafetensorError: Error while deserializing header: MetadataIncompleteBuffer

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\SD\ComfyUI_windows_portable\python_embeded\Lib\site-packages\diffusers\models\model_loading_utils.py", line 153, in load_state_dict
    if f.read().startswith("version"):
       ^^^^^^^^
  File "encodings\cp1252.py", line 23, in decode
UnicodeDecodeError: 'charmap' codec can't decode byte 0x9d in position 300706: character maps to <undefined>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\SD\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-IF_MemoAvatar\IF_MemoCheckpointLoader.py", line 62, in load_checkpoint
    diffusion_net = UNet3DConditionModel.from_pretrained(
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\SD\ComfyUI_windows_portable\python_embeded\Lib\site-packages\huggingface_hub\utils\_validators.py", line 114, in _inner_fn
    return fn(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^
  File "D:\SD\ComfyUI_windows_portable\python_embeded\Lib\site-packages\diffusers\models\modeling_utils.py", line 840, in from_pretrained
    state_dict = load_state_dict(model_file, variant=variant)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\SD\ComfyUI_windows_portable\python_embeded\Lib\site-packages\diffusers\models\model_loading_utils.py", line 165, in load_state_dict
    raise OSError(
OSError: Unable to load weights from checkpoint file for 'D:\SD\ComfyUI_windows_portable\ComfyUI\models\checkpoints\memo\diffusion_net\diffusion_pytorch_model.safetensors' at 'D:\SD\ComfyUI_windows_portable\ComfyUI\models\checkpoints\memo\diffusion_net\diffusion_pytorch_model.safetensors'.
!!! Exception during processing !!! Failed to load models: Unable to load weights from checkpoint file for 'D:\SD\ComfyUI_windows_portable\ComfyUI\models\checkpoints\memo\diffusion_net\diffusion_pytorch_model.safetensors' at 'D:\SD\ComfyUI_windows_portable\ComfyUI\models\checkpoints\memo\diffusion_net\diffusion_pytorch_model.safetensors'.
Traceback (most recent call last):
  File "D:\SD\ComfyUI_windows_portable\python_embeded\Lib\site-packages\diffusers\models\model_loading_utils.py", line 142, in load_state_dict
    return safetensors.torch.load_file(checkpoint_file, device="cpu")
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\SD\ComfyUI_windows_portable\python_embeded\Lib\site-packages\safetensors\torch.py", line 313, in load_file
    with safe_open(filename, framework="pt", device=device) as f:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
safetensors_rust.SafetensorError: Error while deserializing header: MetadataIncompleteBuffer

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\SD\ComfyUI_windows_portable\python_embeded\Lib\site-packages\diffusers\models\model_loading_utils.py", line 153, in load_state_dict
    if f.read().startswith("version"):
       ^^^^^^^^
  File "encodings\cp1252.py", line 23, in decode
UnicodeDecodeError: 'charmap' codec can't decode byte 0x9d in position 300706: character maps to <undefined>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\SD\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-IF_MemoAvatar\IF_MemoCheckpointLoader.py", line 62, in load_checkpoint
    diffusion_net = UNet3DConditionModel.from_pretrained(
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\SD\ComfyUI_windows_portable\python_embeded\Lib\site-packages\huggingface_hub\utils\_validators.py", line 114, in _inner_fn
    return fn(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^
  File "D:\SD\ComfyUI_windows_portable\python_embeded\Lib\site-packages\diffusers\models\modeling_utils.py", line 840, in from_pretrained
    state_dict = load_state_dict(model_file, variant=variant)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\SD\ComfyUI_windows_portable\python_embeded\Lib\site-packages\diffusers\models\model_loading_utils.py", line 165, in load_state_dict
    raise OSError(
OSError: Unable to load weights from checkpoint file for 'D:\SD\ComfyUI_windows_portable\ComfyUI\models\checkpoints\memo\diffusion_net\diffusion_pytorch_model.safetensors' at 'D:\SD\ComfyUI_windows_portable\ComfyUI\models\checkpoints\memo\diffusion_net\diffusion_pytorch_model.safetensors'.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\SD\ComfyUI_windows_portable\ComfyUI\execution.py", line 323, in execute
    output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\SD\ComfyUI_windows_portable\ComfyUI\execution.py", line 198, in get_output_data
    return_values = _map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\SD\ComfyUI_windows_portable\ComfyUI\execution.py", line 169, in _map_node_over_list
    process_inputs(input_dict, i)
  File "D:\SD\ComfyUI_windows_portable\ComfyUI\execution.py", line 158, in process_inputs
    results.append(getattr(obj, func)(**inputs))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\SD\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-IF_MemoAvatar\IF_MemoCheckpointLoader.py", line 120, in load_checkpoint
    raise RuntimeError(f"Failed to load models: {str(e)}")
RuntimeError: Failed to load models: Unable to load weights from checkpoint file for 'D:\SD\ComfyUI_windows_portable\ComfyUI\models\checkpoints\memo\diffusion_net\diffusion_pytorch_model.safetensors' at 'D:\SD\ComfyUI_windows_portable\ComfyUI\models\checkpoints\memo\diffusion_net\diffusion_pytorch_model.safetensors'.

Prompt executed in 1.81 seconds

  
</details>

memo model repository is properly placed in the checkpoint folder.
faceanalisys/models files are duplicated in the faceanalisys folder as you suggested

**Comment by if-ai** [comment]
probably is the omegaconf or some other module missing cos' I forgot to add the full list of reqs earlier sorry 
pip install -r requirements.txt again after updating

**Comment by if-ai** [comment]
should be fix now
