### ISSUE TITLE
Failed to load models - couldn't connect to huggingface and could not find cached files

### ISSUE THREAD

**Issue by smithsun00** [if-ai/ComfyUI-IF_MemoAvatar#10]
Hi

I ran the workflow provided, there was an issue with the IF display text - the package for AI utils failed to load.
I removed it as it is just for showing the status text and replaced it with Show Text.
Then I tried queuing the workflow - there was an error regarding the sd-vae-ft-mse and so I cancelled and downloaded the model files manually.
I set them in the folders as described here and ran it again.
Now I am receiving this error:
`Failed to load models: We couldn't connect to 'https://huggingface.co' to load this model, couldn't find it in the cached files and it looks like F:\AI\ImageGeneration\CUI\ComfyUI_3\ComfyUI\models\vae\sd-vae-ft-mse is not the path to a directory containing a config.json file.
Checkout your internet connection or see how to run the library in offline mode at 'https://huggingface.co/docs/diffusers/installation#offline-mode'`

I will appreciate your help with this, thanks.

**Comment by if-ai** [comment]
do you have a HF token on your environment variables right? ... right?

**Comment by smithsun00** [comment]
I do, yes - but I connected it in relation to another project - but should be ok - I did see some files downloaded before the initial error that caused me to download the model files manually

**Comment by smithsun00** [comment]
Do I need this vae model to be downloaded to the vae fodler?
ComfyUI_3\ComfyUI\models\vae\sd-vae-ft-mse

**Comment by smithsun00** [comment]
It seems this is the code throwing out the error:
# Load VAE
            vae = AutoencoderKL.from_pretrained(
                self.paths["vae"]
            ).to(device=device, dtype=dtype)
            vae.requires_grad_(False)
            vae.eval()

Also - I tested my connection to hugging face - all return 200 and pinging works correctly

Can I ask what is the code trying to load from the vae folder?
because first - it seems to get an incorrect path - adding the sd-vae-ft-mse for some reason, and when I try fixing it manually - it says it cannot find the file diffusion_pytorch_model.bin in there

**Comment by smithsun00** [comment]
Ok, now downloading the named vae bin file under the required name solved that issue.
But now I am coming across different issue:
omegaconf.errors.ConfigKeyError: Missing key tokenizer_conf
Here is the stack trace
`Downloading emotion2vec models from modelscope
Traceback (most recent call last):
  File "F:\AI\ImageGeneration\CUI\ComfyUI_3\ComfyUI\custom_nodes\ComfyUI-IF_MemoAvatar\IF_MemoAvatar.py", line 139, in generate
    audio_emotion, num_emotion_classes = extract_audio_emotion_labels(
                                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\AI\ImageGeneration\CUI\ComfyUI_3\python_embeded\Lib\site-packages\torch\utils\_contextlib.py", line 116, in decorate_context
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "F:\AI\ImageGeneration\CUI\ComfyUI_3\ComfyUI\custom_nodes\ComfyUI-IF_MemoAvatar\memo\utils\audio_utils.py", line 174, in extract_audio_emotion_labels
    kwargs = download_model(model=emotion2vec_model)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\AI\ImageGeneration\CUI\ComfyUI_3\python_embeded\Lib\site-packages\funasr\download\download_from_hub.py", line 11, in download_model
    kwargs = download_from_ms(**kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\AI\ImageGeneration\CUI\ComfyUI_3\python_embeded\Lib\site-packages\funasr\download\download_from_hub.py", line 67, in download_from_ms
    kwargs["tokenizer_conf"]["token_list"] = os.path.join(model_or_path, "tokens.txt")
    ~~~~~~^^^^^^^^^^^^^^^^^^
  File "F:\AI\ImageGeneration\CUI\ComfyUI_3\python_embeded\Lib\site-packages\omegaconf\dictconfig.py", line 375, in __getitem__
    self._format_and_raise(key=key, value=None, cause=e)
  File "F:\AI\ImageGeneration\CUI\ComfyUI_3\python_embeded\Lib\site-packages\omegaconf\base.py", line 231, in _format_and_raise
    format_and_raise(
  File "F:\AI\ImageGeneration\CUI\ComfyUI_3\python_embeded\Lib\site-packages\omegaconf\_utils.py", line 899, in format_and_raise
    _raise(ex, cause)
  File "F:\AI\ImageGeneration\CUI\ComfyUI_3\python_embeded\Lib\site-packages\omegaconf\_utils.py", line 797, in _raise
    raise ex.with_traceback(sys.exc_info()[2])  # set env var OC_CAUSE=1 for full trace
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\AI\ImageGeneration\CUI\ComfyUI_3\python_embeded\Lib\site-packages\omegaconf\dictconfig.py", line 369, in __getitem__
    return self._get_impl(key=key, default_value=_DEFAULT_MARKER_)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\AI\ImageGeneration\CUI\ComfyUI_3\python_embeded\Lib\site-packages\omegaconf\dictconfig.py", line 442, in _get_impl
    node = self._get_child(
           ^^^^^^^^^^^^^^^^
  File "F:\AI\ImageGeneration\CUI\ComfyUI_3\python_embeded\Lib\site-packages\omegaconf\basecontainer.py", line 73, in _get_child
    child = self._get_node(
            ^^^^^^^^^^^^^^^
  File "F:\AI\ImageGeneration\CUI\ComfyUI_3\python_embeded\Lib\site-packages\omegaconf\dictconfig.py", line 480, in _get_node
    raise ConfigKeyError(f"Missing key {key!s}")`

I tried updating the funasr package - but than it caused another failure on the 'funasr\download\download_from_hub'

Not sure where to go from here

**Comment by if-ai** [comment]
I modified it again I think it was the use safetensors flag to true on the vae

**Comment by ioritree** [comment]
update to last then
Failed to load models: Error no file named diffusion_pytorch_model.safetensors found in directory X:\AI\ComfyUI_windows_portable\ComfyUI\models\checkpoints\memo.
