### ISSUE TITLE
TypeError: unsupported operand type(s) for -: 'NoneType' and 'int'

### ISSUE THREAD

**Issue by weidi1987** [if-ai/ComfyUI-IF_MemoAvatar#16]
Python Version: 3.12.7
PyTorch Version: 2.4.1+cu124
FFmpeg installed: ffmpeg version N-109957-g373ef1c4fa-20230302 Copyright (c) 2000-2023 the FFmpeg developers
ONNX Runtime GPU package installed with version: 1.20.1
CUDA is available in Torch, setting Torch device to CUDA
ONNXruntime has CUDAExecutionProvider available, enabling acceleration
Loading model Kim_Vocal_2.onnx...
Model converted from onnx to pytorch due to segment size not matching dim_t, processing may be slower.
Load model duration: 00:00:01
Starting separation process for audio_file_path: D:\AI\3.11\ComfyUI_windows_portable_nvidia\ComfyUI_windows_portable\ComfyUI\temp\memo_audio_cache\resampled_1734493529.5729995-16k.wav
Traceback (most recent call last):
  File "D:\AI\3.11\ComfyUI_windows_portable_nvidia\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-IF_MemoAvatar\IF_MemoAvatar.py", line 128, in generate
    audio_emb, audio_length = preprocess_audio(
                              ^^^^^^^^^^^^^^^^^
  File "D:\AI\3.11\ComfyUI_windows_portable_nvidia\ComfyUI_windows_portable\python_embeded\Lib\site-packages\torch\utils\_contextlib.py", line 116, in decorate_context
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "D:\AI\3.11\ComfyUI_windows_portable_nvidia\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-IF_MemoAvatar\memo\utils\audio_utils.py", line 94, in preprocess_audio
    outputs = vocal_separator.separate(wav_path)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\AI\3.11\ComfyUI_windows_portable_nvidia\ComfyUI_windows_portable\python_embeded\Lib\site-packages\audio_separator\separator\separator.py", line 743, in separate
    output_files = self.model_instance.separate(audio_file_path, custom_output_names)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\AI\3.11\ComfyUI_windows_portable_nvidia\ComfyUI_windows_portable\python_embeded\Lib\site-packages\audio_separator\separator\architectures\mdx_separator.py", line 158, in separate
    source = self.demix(mix)
             ^^^^^^^^^^^^^^^
  File "D:\AI\3.11\ComfyUI_windows_portable_nvidia\ComfyUI_windows_portable\python_embeded\Lib\site-packages\audio_separator\separator\architectures\mdx_separator.py", line 296, in demix
    self.initialize_model_settings()
  File "D:\AI\3.11\ComfyUI_windows_portable_nvidia\ComfyUI_windows_portable\python_embeded\Lib\site-packages\audio_separator\separator\architectures\mdx_separator.py", line 224, in initialize_model_settings
    self.chunk_size = self.hop_length * (self.segment_size - 1)
                                         ~~~~~~~~~~~~~~~~~~^~~
TypeError: unsupported operand type(s) for -: 'NoneType' and 'int'
Prompt executed in 45.95 seconds

**Comment by if-ai** [comment]
I need to check the onnxruntime probably move them to cpu I thought they were like that by default. I need to do that for optiumization next so. maybe when I add that feature it will be solved for now I am not too sure also make sure you have 
audio-separator             0.24.1
`pip install audio-separator `
