### ISSUE TITLE
Missing Node Types

### ISSUE THREAD

**Issue by ioritree** [if-ai/ComfyUI-IF_MemoAvatar#2]
Platform: Windows
Python version: 3.12.7 (tags/v3.12.7:0b05ead, Oct  1 2024, 03:06:41) [MSC v.1941 64 bit (AMD64)]
pytorch version: 2.5.1+cu124
xformers version: 0.0.28.post3
Device: cuda:0 NVIDIA GeForce RTX 3090 : cudaMallocAsync
Using xformers cross attention

```
Traceback (most recent call last):
  File "G:\AI\ComfyUI_windows_portable\ComfyUI\nodes.py", line 2035, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "G:\AI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-IF_MemoAvatar\__init__.py", line 23, in <module>
    from .IF_MemoAvatar import IF_MemoAvatar
  File "G:\AI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-IF_MemoAvatar\IF_MemoAvatar.py", line 17, in <module>
    from memo.utils.audio_utils import extract_audio_emotion_labels, preprocess_audio, resample_audio
  File "G:\AI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-IF_MemoAvatar\memo\utils\audio_utils.py", line 14, in <module>
    from funasr.download.download_from_hub import download_model
ModuleNotFoundError: No module named 'funasr.download.download_from_hub'

Cannot import G:\AI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-IF_MemoAvatar module for custom nodes: No module named 'funasr.download.download_from_hub'
```

**When loading the graph, the following node types were not found**

**IF MemoCheckpointLoader
IF_MemoAvatar**

**Comment by if-ai** [comment]
I forgot to add some more reqs to the requirements.txt it looks like you are missing some modules as consquence sorry you can activate the venv and 
`pip install -r requirements.txt`

**Comment by 1blackbar** [comment]
dev are you kidding ?

**Comment by 1696hh** [comment]
根本无法安装

**Comment by if-ai** [comment]
> dev are you kidding ?

the exact module he is missing is this `pip install funasr==1.0.27` I forgot to add it on the first commit

**Comment by if-ai** [comment]
also move into the 
cd X:\ComfyUI\custom_nodes\ComfyUI-IF_MemoAvatar\
and do a `git pull` I fixed many issues on the last update

**Comment by 1696hh** [comment]
(IMPORT FAILED): D:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-IF_MemoAvatar
As usual, it won't load at all. It keeps giving me errors.

**Comment by mykeehu** [comment]
Install an older version of moviepy: 
`pip install moviepy==1.0.3`

My problem is that it doesn't download the models and I can't find where it should.

**Comment by if-ai** [comment]
> Install an older version of moviepy: `pip install moviepy==1.0.3`
> 
> My problem is that it doesn't download the models and I can't find where it should.

the latest version is downloading the models automatically
