### ISSUE TITLE
python\lib\subprocess.py", line 1456, in _execute_child     hp, ht, pid, tid = _winapi.CreateProcess(executable, args, FileNotFoundError: [WinError 2] 

### ISSUE THREAD

**Issue by zaitaxiang2012** [if-ai/ComfyUI-IF_MemoAvatar#24]
During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "F:\ComfyUI-aki-v1.3-shuziren0912\custom_nodes\ComfyUI-IF_MemoAvatar-main\IF_MemoAvatar.py", line 140, in generate
    audio_emotion, num_emotion_classes = extract_audio_emotion_labels(
  File "F:\ComfyUI-aki-v1.3-shuziren0912\python\lib\site-packages\torch\utils\_contextlib.py", line 116, in decorate_context
    return func(*args, **kwargs)
  File "F:\ComfyUI-aki-v1.3-shuziren0912\custom_nodes\ComfyUI-IF_MemoAvatar-main\memo\utils\audio_utils.py", line 164, in extract_audio_emotion_labels
    kwargs = download_model(model=emotion2vec_model)
  File "F:\ComfyUI-aki-v1.3-shuziren0912\python\lib\site-packages\funasr\download\download_from_hub.py", line 11, in download_model
    kwargs = download_from_ms(**kwargs)
  File "F:\ComfyUI-aki-v1.3-shuziren0912\python\lib\site-packages\funasr\download\download_from_hub.py", line 86, in download_from_ms
    install_requirements(requirements)
  File "F:\ComfyUI-aki-v1.3-shuziren0912\python\lib\site-packages\funasr\utils\install_model_requirements.py", line 22, in install_requirements
    result = subprocess.run(
  File "F:\ComfyUI-aki-v1.3-shuziren0912\python\lib\subprocess.py", line 503, in run
    with Popen(*popenargs, **kwargs) as process:
  File "<enhanced_experience vendors.sentry_sdk.utils>", line 1720, in runner
  File "<enhanced_experience vendors.sentry_sdk.integrations.stdlib>", line 224, in sentry_patched_popen_init
  File "F:\ComfyUI-aki-v1.3-shuziren0912\python\lib\subprocess.py", line 971, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "F:\ComfyUI-aki-v1.3-shuziren0912\python\lib\subprocess.py", line 1456, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
FileNotFoundError: [WinError 2] 
Prompt executed in 5.72 seconds

**Comment by AncientCousin** [comment]
Same issue,help
