### ISSUE TITLE
What file cannot be found?help

### ISSUE THREAD

**Issue by AncientCousin** [if-ai/ComfyUI-IF_MemoAvatar#26]
Traceback (most recent call last):
  File "C:\Softwares\ComfyUI\ComfyUI-1214\memoAvatar\MemoAvatorl-oneky-T8\MemoAvatorl-oneky-T8\ComfyUI\custom_nodes\ComfyUI-IF_MemoAvatar\IF_MemoAvatar.py", line 126, in generate
    resampled_path = resample_audio(temp_audio, resampled_path)
  File "C:\Softwares\ComfyUI\ComfyUI-1214\memoAvatar\MemoAvatorl-oneky-T8\MemoAvatorl-oneky-T8\ComfyUI\custom_nodes\ComfyUI-IF_MemoAvatar\memo\utils\audio_utils.py", line 27, in resample_audio
    p = subprocess.Popen(
  File "C:\Softwares\ComfyUI\ComfyUI-1214\memoAvatar\MemoAvatorl-oneky-T8\MemoAvatorl-oneky-T8\ComfyUI\Python\lib\subprocess.py", line 971, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "C:\Softwares\ComfyUI\ComfyUI-1214\memoAvatar\MemoAvatorl-oneky-T8\MemoAvatorl-oneky-T8\ComfyUI\Python\lib\subprocess.py", line 1456, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
FileNotFoundError: [WinError 2] 系统找不到指定的文件。
[EasyUse] Save Text: No file details found. No file output.
Prompt executed in 10.97 seconds

**Comment by if-ai** [comment]
you probably missed the ffmpg installation 
this normally should have been taking care of on ther requirements.txt
activate your env and make sure to have the directory for ffmpg on the environment path
`micromamba install ffmpeg -c conda-forge`

**Comment by AncientCousin** [comment]
Problem solved,I forgot to add the path,my bad,tk u so much!
