### ISSUE TITLE
Failed to load models: Error no file named config.json found in directory

### ISSUE THREAD

**Issue by dvoidus** [if-ai/ComfyUI-IF_MemoAvatar#5]
```
# ComfyUI Error Report
## Error Details
- **Node ID:** 32
- **Node Type:** IF_MemoCheckpointLoader
- **Exception Type:** RuntimeError
- **Exception Message:** Failed to load models: Error no file named config.json found in directory C:\comfyui\ComfyUI\models\checkpoints\memo.
```

I'm getting the following error

```
got prompt
Loading models
Error loading models: Error no file named config.json found in directory C:\comfyui\ComfyUI\models\checkpoints\memo.
Traceback (most recent call last):
  File "C:\comfyui\ComfyUI\custom_nodes\ComfyUI-IF_MemoAvatar\IF_MemoCheckpointLoader.py", line 53, in load_checkpoint
    reference_net = UNet2DConditionModel.from_pretrained(
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\comfyui\python_embeded\Lib\site-packages\huggingface_hub\utils\_validators.py", line 114, in _inner_fn
    return fn(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^
  File "C:\comfyui\python_embeded\Lib\site-packages\diffusers\models\modeling_utils.py", line 640, in from_pretrained
    config, unused_kwargs, commit_hash = cls.load_config(
                                         ^^^^^^^^^^^^^^^^
  File "C:\comfyui\python_embeded\Lib\site-packages\huggingface_hub\utils\_validators.py", line 114, in _inner_fn
    return fn(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^
  File "C:\comfyui\python_embeded\Lib\site-packages\diffusers\configuration_utils.py", line 373, in load_config
    raise EnvironmentError(
OSError: Error no file named config.json found in directory C:\comfyui\ComfyUI\models\checkpoints\memo.
!!! Exception during processing !!! Failed to load models: Error no file named config.json found in directory C:\comfyui\ComfyUI\models\checkpoints\memo.
Traceback (most recent call last):
  File "C:\comfyui\ComfyUI\custom_nodes\ComfyUI-IF_MemoAvatar\IF_MemoCheckpointLoader.py", line 53, in load_checkpoint
    reference_net = UNet2DConditionModel.from_pretrained(
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\comfyui\python_embeded\Lib\site-packages\huggingface_hub\utils\_validators.py", line 114, in _inner_fn
    return fn(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^
  File "C:\comfyui\python_embeded\Lib\site-packages\diffusers\models\modeling_utils.py", line 640, in from_pretrained
    config, unused_kwargs, commit_hash = cls.load_config(
                                         ^^^^^^^^^^^^^^^^
  File "C:\comfyui\python_embeded\Lib\site-packages\huggingface_hub\utils\_validators.py", line 114, in _inner_fn
    return fn(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^
  File "C:\comfyui\python_embeded\Lib\site-packages\diffusers\configuration_utils.py", line 373, in load_config
    raise EnvironmentError(
OSError: Error no file named config.json found in directory C:\comfyui\ComfyUI\models\checkpoints\memo.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\comfyui\ComfyUI\execution.py", line 324, in execute
    output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\comfyui\ComfyUI\execution.py", line 199, in get_output_data
    return_values = _map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\comfyui\ComfyUI\execution.py", line 170, in _map_node_over_list
    process_inputs(input_dict, i)
  File "C:\comfyui\ComfyUI\execution.py", line 159, in process_inputs
    results.append(getattr(obj, func)(**inputs))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\comfyui\ComfyUI\custom_nodes\ComfyUI-IF_MemoAvatar\IF_MemoCheckpointLoader.py", line 120, in load_checkpoint
    raise RuntimeError(f"Failed to load models: {str(e)}")
RuntimeError: Failed to load models: Error no file named config.json found in directory C:\comfyui\ComfyUI\models\checkpoints\memo.

Prompt executed in 0.24 seconds
```

**Comment by wsxedcr** [comment]
I have the same problem

**Comment by if-ai** [comment]
do you guys had the latest update?

**Comment by Siziff** [comment]
@if-ai  yes, same problem

**Comment by if-ai** [comment]
I added a new fix for the auto download models  and fixed the paths if is not that open the issue again. Thanks
