### ISSUE TITLE
Failed in nopython mode pipeline (step: nopython frontend)

### ISSUE THREAD

**Issue by cheezecrisp** [if-ai/ComfyUI-IF_MemoAvatar#9]
got prompt
Loading models
The config attributes {'center_input_sample': False, 'out_channels': 4} were passed to UNet2DConditionModel, but are not expected and will be ignored. Please verify your config.json configuration file.
The config attributes {'addition_embed_type': None, 'addition_embed_type_num_heads': 64, 'addition_time_embed_dim': None, 'attention_type': 'default', 'center_input_sample': False, 'class_embeddings_concat': False, 'conv_in_kernel': 3, 'dropout': 0.0, 'encoder_hid_dim': None, 'encoder_hid_dim_type': None, 'mid_block_only_cross_attention': None, 'num_attention_heads': None, 'projection_class_embeddings_input_dim': None, 'reverse_transformer_layers_per_block': None, 'time_cond_proj_dim': None, 'time_embedding_act_fn': None, 'time_embedding_dim': None, 'time_embedding_type': 'positional', 'timestep_post_act': None, 'transformer_layers_per_block': 1} were passed to UNet3DConditionModel, but are not expected and will be ignored. Please verify your config.json configuration file.
Models loaded successfully to cuda with dtype torch.float16
face_models path: D:\AI\ComfyUI_windows_portable\ComfyUI\models\checkpoints\memo\misc\face_analysis
Applied providers: ['CUDAExecutionProvider', 'CPUExecutionProvider'], with options: {'CUDAExecutionProvider': {'device_id': '0', 'has_user_compute_stream': '0', 'cudnn_conv1d_pad_to_nc1d': '0', 'user_compute_stream': '0', 'gpu_external_alloc': '0', 'gpu_mem_limit': '18446744073709551615', 'enable_cuda_graph': '0', 'gpu_external_free': '0', 'gpu_external_empty_cache': '0', 'arena_extend_strategy': 'kNextPowerOfTwo', 'cudnn_conv_algo_search': 'EXHAUSTIVE', 'do_copy_in_default_stream': '1', 'cudnn_conv_use_max_workspace': '1', 'tunable_op_enable': '0', 'tunable_op_tuning_enable': '0', 'tunable_op_max_tuning_duration_ms': '0', 'enable_skip_layer_norm_strict_mode': '0', 'prefer_nhwc': '0', 'use_ep_level_unified_stream': '0', 'use_tf32': '1', 'sdpa_kernel': '0', 'fuse_conv_bias': '0'}, 'CPUExecutionProvider': {}}
find model: D:\AI\ComfyUI_windows_portable\ComfyUI\models\checkpoints\memo\misc\face_analysis\models\1k3d68.onnx landmark_3d_68 ['None', 3, 192, 192] 0.0 1.0
Applied providers: ['CUDAExecutionProvider', 'CPUExecutionProvider'], with options: {'CUDAExecutionProvider': {'device_id': '0', 'has_user_compute_stream': '0', 'cudnn_conv1d_pad_to_nc1d': '0', 'user_compute_stream': '0', 'gpu_external_alloc': '0', 'gpu_mem_limit': '18446744073709551615', 'enable_cuda_graph': '0', 'gpu_external_free': '0', 'gpu_external_empty_cache': '0', 'arena_extend_strategy': 'kNextPowerOfTwo', 'cudnn_conv_algo_search': 'EXHAUSTIVE', 'do_copy_in_default_stream': '1', 'cudnn_conv_use_max_workspace': '1', 'tunable_op_enable': '0', 'tunable_op_tuning_enable': '0', 'tunable_op_max_tuning_duration_ms': '0', 'enable_skip_layer_norm_strict_mode': '0', 'prefer_nhwc': '0', 'use_ep_level_unified_stream': '0', 'use_tf32': '1', 'sdpa_kernel': '0', 'fuse_conv_bias': '0'}, 'CPUExecutionProvider': {}}
find model: D:\AI\ComfyUI_windows_portable\ComfyUI\models\checkpoints\memo\misc\face_analysis\models\2d106det.onnx landmark_2d_106 ['None', 3, 192, 192] 0.0 1.0
Applied providers: ['CUDAExecutionProvider', 'CPUExecutionProvider'], with options: {'CUDAExecutionProvider': {'device_id': '0', 'has_user_compute_stream': '0', 'cudnn_conv1d_pad_to_nc1d': '0', 'user_compute_stream': '0', 'gpu_external_alloc': '0', 'gpu_mem_limit': '18446744073709551615', 'enable_cuda_graph': '0', 'gpu_external_free': '0', 'gpu_external_empty_cache': '0', 'arena_extend_strategy': 'kNextPowerOfTwo', 'cudnn_conv_algo_search': 'EXHAUSTIVE', 'do_copy_in_default_stream': '1', 'cudnn_conv_use_max_workspace': '1', 'tunable_op_enable': '0', 'tunable_op_tuning_enable': '0', 'tunable_op_max_tuning_duration_ms': '0', 'enable_skip_layer_norm_strict_mode': '0', 'prefer_nhwc': '0', 'use_ep_level_unified_stream': '0', 'use_tf32': '1', 'sdpa_kernel': '0', 'fuse_conv_bias': '0'}, 'CPUExecutionProvider': {}}
find model: D:\AI\ComfyUI_windows_portable\ComfyUI\models\checkpoints\memo\misc\face_analysis\models\genderage.onnx genderage ['None', 3, 96, 96] 0.0 1.0
Applied providers: ['CUDAExecutionProvider', 'CPUExecutionProvider'], with options: {'CUDAExecutionProvider': {'device_id': '0', 'has_user_compute_stream': '0', 'cudnn_conv1d_pad_to_nc1d': '0', 'user_compute_stream': '0', 'gpu_external_alloc': '0', 'gpu_mem_limit': '18446744073709551615', 'enable_cuda_graph': '0', 'gpu_external_free': '0', 'gpu_external_empty_cache': '0', 'arena_extend_strategy': 'kNextPowerOfTwo', 'cudnn_conv_algo_search': 'EXHAUSTIVE', 'do_copy_in_default_stream': '1', 'cudnn_conv_use_max_workspace': '1', 'tunable_op_enable': '0', 'tunable_op_tuning_enable': '0', 'tunable_op_max_tuning_duration_ms': '0', 'enable_skip_layer_norm_strict_mode': '0', 'prefer_nhwc': '0', 'use_ep_level_unified_stream': '0', 'use_tf32': '1', 'sdpa_kernel': '0', 'fuse_conv_bias': '0'}, 'CPUExecutionProvider': {}}
find model: D:\AI\ComfyUI_windows_portable\ComfyUI\models\checkpoints\memo\misc\face_analysis\models\glintr100.onnx recognition ['None', 3, 112, 112] 127.5 127.5
Applied providers: ['CUDAExecutionProvider', 'CPUExecutionProvider'], with options: {'CUDAExecutionProvider': {'device_id': '0', 'has_user_compute_stream': '0', 'cudnn_conv1d_pad_to_nc1d': '0', 'user_compute_stream': '0', 'gpu_external_alloc': '0', 'gpu_mem_limit': '18446744073709551615', 'enable_cuda_graph': '0', 'gpu_external_free': '0', 'gpu_external_empty_cache': '0', 'arena_extend_strategy': 'kNextPowerOfTwo', 'cudnn_conv_algo_search': 'EXHAUSTIVE', 'do_copy_in_default_stream': '1', 'cudnn_conv_use_max_workspace': '1', 'tunable_op_enable': '0', 'tunable_op_tuning_enable': '0', 'tunable_op_max_tuning_duration_ms': '0', 'enable_skip_layer_norm_strict_mode': '0', 'prefer_nhwc': '0', 'use_ep_level_unified_stream': '0', 'use_tf32': '1', 'sdpa_kernel': '0', 'fuse_conv_bias': '0'}, 'CPUExecutionProvider': {}}
find model: D:\AI\ComfyUI_windows_portable\ComfyUI\models\checkpoints\memo\misc\face_analysis\models\scrfd_10g_bnkps.onnx detection [1, 3, '?', '?'] 127.5 128.0
set det-size: (640, 640)
Some weights of Wav2VecModel were not initialized from the model checkpoint at D:\AI\ComfyUI_windows_portable\ComfyUI\models\wav2vec\facebook\wav2vec2-base-960h and are newly initialized: ['wav2vec2.masked_spec_embed']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.
Separator version 0.24.1 instantiating with output_dir: D:\AI\ComfyUI_windows_portable\ComfyUI\temp\memo_audio_cache, output_format: WAV
Operating System: Windows 10.0.19045
System: Windows Node: DESKTOP-71G10M9 Release: 10 Machine: AMD64 Proc: AMD64 Family 25 Model 33 Stepping 2, AuthenticAMD
Python Version: 3.11.6
PyTorch Version: 2.5.1+cu124
FFmpeg installed: ffmpeg version 2023-02-13-git-2296078397-essentials_build-www.gyan.dev Copyright (c) 2000-2023 the FFmpeg developers
ONNX Runtime GPU package installed with version: 1.20.1
ONNX Runtime CPU package installed with version: 1.15.1
CUDA is available in Torch, setting Torch device to CUDA
ONNXruntime has CUDAExecutionProvider available, enabling acceleration
Loading model Kim_Vocal_2.onnx...
Load model duration: 00:00:00
Starting separation process for audio_file_path: D:\AI\ComfyUI_windows_portable\ComfyUI\temp\memo_audio_cache\audio_093422_temp-16k.wav
Traceback (most recent call last):
  File "D:\AI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-IF_MemoAvatar\IF_MemoAvatar.py", line 121, in generate
    audio_emb, audio_length = preprocess_audio(
                              ^^^^^^^^^^^^^^^^^
  File "D:\AI\ComfyUI_windows_portable\python_embeded\Lib\site-packages\torch\utils\_contextlib.py", line 116, in decorate_context
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "D:\AI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-IF_MemoAvatar\memo\utils\audio_utils.py", line 94, in preprocess_audio
    outputs = vocal_separator.separate(wav_path)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\AI\ComfyUI_windows_portable\python_embeded\Lib\site-packages\audio_separator\separator\separator.py", line 774, in separate
    output_files = self.model_instance.separate(audio_file_path, primary_output_name, secondary_output_name)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\AI\ComfyUI_windows_portable\python_embeded\Lib\site-packages\audio_separator\separator\architectures\mdx_separator.py", line 153, in separate
    mix = self.prepare_mix(self.audio_file_path)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\AI\ComfyUI_windows_portable\python_embeded\Lib\site-packages\audio_separator\separator\common_separator.py", line 207, in prepare_mix
    mix, sr = librosa.load(mix, mono=False, sr=self.sample_rate)
              ^^^^^^^^^^^^
  File "D:\AI\ComfyUI_windows_portable\python_embeded\Lib\site-packages\lazy_loader\__init__.py", line 78, in __getattr__
    attr = getattr(submod, name)
           ^^^^^^^^^^^^^^^^^^^^^
  File "D:\AI\ComfyUI_windows_portable\python_embeded\Lib\site-packages\lazy_loader\__init__.py", line 77, in __getattr__
    submod = importlib.import_module(submod_path)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "importlib\__init__.py", line 126, in import_module
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "D:\AI\ComfyUI_windows_portable\python_embeded\Lib\site-packages\librosa\core\audio.py", line 1158, in <module>
    @guvectorize(
     ^^^^^^^^^^^^
  File "D:\AI\ComfyUI_windows_portable\python_embeded\Lib\site-packages\numba\np\ufunc\decorators.py", line 203, in wrap
    guvec.add(fty)
  File "D:\AI\ComfyUI_windows_portable\python_embeded\Lib\site-packages\numba\np\ufunc\gufunc.py", line 64, in add
    self.gufunc_builder.add(fty)
  File "D:\AI\ComfyUI_windows_portable\python_embeded\Lib\site-packages\numba\np\ufunc\ufuncbuilder.py", line 258, in add
    cres, args, return_type = _compile_element_wise_function(
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\AI\ComfyUI_windows_portable\python_embeded\Lib\site-packages\numba\np\ufunc\ufuncbuilder.py", line 176, in _compile_element_wise_function
    cres = nb_func.compile(sig, **targetoptions)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\AI\ComfyUI_windows_portable\python_embeded\Lib\site-packages\numba\np\ufunc\ufuncbuilder.py", line 124, in compile
    return self._compile_core(sig, flags, locals)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\AI\ComfyUI_windows_portable\python_embeded\Lib\site-packages\numba\np\ufunc\ufuncbuilder.py", line 157, in _compile_core
    cres = compiler.compile_extra(typingctx, targetctx,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\AI\ComfyUI_windows_portable\python_embeded\Lib\site-packages\numba\core\compiler.py", line 770, in compile_extra
    return pipeline.compile_extra(func)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\AI\ComfyUI_windows_portable\python_embeded\Lib\site-packages\numba\core\compiler.py", line 461, in compile_extra
    return self._compile_bytecode()
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\AI\ComfyUI_windows_portable\python_embeded\Lib\site-packages\numba\core\compiler.py", line 529, in _compile_bytecode
    return self._compile_core()
           ^^^^^^^^^^^^^^^^^^^^
  File "D:\AI\ComfyUI_windows_portable\python_embeded\Lib\site-packages\numba\core\compiler.py", line 508, in _compile_core
    raise e
  File "D:\AI\ComfyUI_windows_portable\python_embeded\Lib\site-packages\numba\core\compiler.py", line 495, in _compile_core
    pm.run(self.state)
  File "D:\AI\ComfyUI_windows_portable\python_embeded\Lib\site-packages\numba\core\compiler_machinery.py", line 368, in run
    raise patched_exception
  File "D:\AI\ComfyUI_windows_portable\python_embeded\Lib\site-packages\numba\core\compiler_machinery.py", line 356, in run
    self._runPass(idx, pass_inst, state)
  File "D:\AI\ComfyUI_windows_portable\python_embeded\Lib\site-packages\numba\core\compiler_lock.py", line 35, in _acquire_compile_lock
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "D:\AI\ComfyUI_windows_portable\python_embeded\Lib\site-packages\numba\core\compiler_machinery.py", line 311, in _runPass
    mutated |= check(pss.run_pass, internal_state)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\AI\ComfyUI_windows_portable\python_embeded\Lib\site-packages\numba\core\compiler_machinery.py", line 273, in check
    mangled = func(compiler_state)
              ^^^^^^^^^^^^^^^^^^^^
  File "D:\AI\ComfyUI_windows_portable\python_embeded\Lib\site-packages\numba\core\typed_passes.py", line 466, in run_pass
    lower.lower()
  File "D:\AI\ComfyUI_windows_portable\python_embeded\Lib\site-packages\numba\core\lowering.py", line 187, in lower
    self.lower_normal_function(self.fndesc)
  File "D:\AI\ComfyUI_windows_portable\python_embeded\Lib\site-packages\numba\core\lowering.py", line 241, in lower_normal_function
    entry_block_tail = self.lower_function_body()
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\AI\ComfyUI_windows_portable\python_embeded\Lib\site-packages\numba\core\lowering.py", line 271, in lower_function_body
    self.lower_block(block)
  File "D:\AI\ComfyUI_windows_portable\python_embeded\Lib\site-packages\numba\core\lowering.py", line 285, in lower_block
    self.lower_inst(inst)
  File "D:\AI\ComfyUI_windows_portable\python_embeded\Lib\site-packages\numba\core\lowering.py", line 463, in lower_inst
    val = self.lower_assign(ty, inst)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\AI\ComfyUI_windows_portable\python_embeded\Lib\site-packages\numba\core\lowering.py", line 675, in lower_assign
    return self.lower_expr(ty, value)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\AI\ComfyUI_windows_portable\python_embeded\Lib\site-packages\numba\core\lowering.py", line 1211, in lower_expr
    res = self.lower_call(resty, expr)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\AI\ComfyUI_windows_portable\python_embeded\Lib\site-packages\numba\core\lowering.py", line 940, in lower_call
    res = self._lower_call_normal(fnty, expr, signature)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\AI\ComfyUI_windows_portable\python_embeded\Lib\site-packages\numba\core\lowering.py", line 1182, in _lower_call_normal
    res = impl(self.builder, argvals, self.loc)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\AI\ComfyUI_windows_portable\python_embeded\Lib\site-packages\numba\core\base.py", line 1187, in __call__
    res = self._imp(self._context, builder, self._sig, args, loc=loc)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\AI\ComfyUI_windows_portable\python_embeded\Lib\site-packages\numba\core\base.py", line 1217, in wrapper
    return fn(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^
  File "D:\AI\ComfyUI_windows_portable\python_embeded\Lib\site-packages\numba\stencils\stencil.py", line 30, in __call__
    cres = self.stencilFunc.compile_for_argtys(sig.args, {},
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\AI\ComfyUI_windows_portable\python_embeded\Lib\site-packages\numba\stencils\stencil.py", line 370, in compile_for_argtys
    new_func = self._stencil_wrapper(result, sigret, return_type,
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\AI\ComfyUI_windows_portable\python_embeded\Lib\site-packages\numba\stencils\stencil.py", line 758, in _stencil_wrapper
    new_func = compiler.compile_ir(
               ^^^^^^^^^^^^^^^^^^^^
  File "D:\AI\ComfyUI_windows_portable\python_embeded\Lib\site-packages\numba\core\compiler.py", line 833, in compile_ir
    return pipeline.compile_ir(func_ir=func_ir, lifted=lifted,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\AI\ComfyUI_windows_portable\python_embeded\Lib\site-packages\numba\core\compiler.py", line 471, in compile_ir
    return self._compile_ir()
           ^^^^^^^^^^^^^^^^^^
  File "D:\AI\ComfyUI_windows_portable\python_embeded\Lib\site-packages\numba\core\compiler.py", line 536, in _compile_ir
    return self._compile_core()
           ^^^^^^^^^^^^^^^^^^^^
  File "D:\AI\ComfyUI_windows_portable\python_embeded\Lib\site-packages\numba\core\compiler.py", line 508, in _compile_core
    raise e
  File "D:\AI\ComfyUI_windows_portable\python_embeded\Lib\site-packages\numba\core\compiler.py", line 495, in _compile_core
    pm.run(self.state)
  File "D:\AI\ComfyUI_windows_portable\python_embeded\Lib\site-packages\numba\core\compiler_machinery.py", line 368, in run
    raise patched_exception
  File "D:\AI\ComfyUI_windows_portable\python_embeded\Lib\site-packages\numba\core\compiler_machinery.py", line 356, in run
    self._runPass(idx, pass_inst, state)
  File "D:\AI\ComfyUI_windows_portable\python_embeded\Lib\site-packages\numba\core\compiler_lock.py", line 35, in _acquire_compile_lock
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "D:\AI\ComfyUI_windows_portable\python_embeded\Lib\site-packages\numba\core\compiler_machinery.py", line 311, in _runPass
    mutated |= check(pss.run_pass, internal_state)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\AI\ComfyUI_windows_portable\python_embeded\Lib\site-packages\numba\core\compiler_machinery.py", line 273, in check
    mangled = func(compiler_state)
              ^^^^^^^^^^^^^^^^^^^^
  File "D:\AI\ComfyUI_windows_portable\python_embeded\Lib\site-packages\numba\core\typed_passes.py", line 110, in run_pass
    typemap, return_type, calltypes, errs = type_inference_stage(
                                            ^^^^^^^^^^^^^^^^^^^^^
  File "D:\AI\ComfyUI_windows_portable\python_embeded\Lib\site-packages\numba\core\typed_passes.py", line 91, in type_inference_stage
    errs = infer.propagate(raise_errors=raise_errors)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\AI\ComfyUI_windows_portable\python_embeded\Lib\site-packages\numba\core\typeinfer.py", line 1086, in propagate
    raise errors[0]
numba.core.errors.TypingError: Failed in nopython mode pipeline (step: native lowering)
Failed in nopython mode pipeline (step: nopython frontend)
No implementation of function Function(<built-in function empty>) found for signature:

 >>> empty(UniTuple(int64 x 1), dtype=class(bool))

There are 2 candidate implementations:
    - Of which 2 did not match due to:
    Overload in function 'ol_np_empty': File: numba\np\arrayobj.py: Line 4355.
      With argument(s): '(UniTuple(int64 x 1), dtype=class(bool))':
     Rejected as the implementation raised a specific error:
       RecursionError: maximum recursion depth exceeded while calling a Python object
  raised from linecache.py:88

During: resolving callee type: Function(<built-in function empty>)
During: typing of call at <string> (3)

File "<string>", line 3:
<source missing, REPL/exec in use?>

During: lowering "$26call.5 = call $4load_global.0(x, threshold, zero_pos, func=$4load_global.0, args=[Var(x, audio.py:1158), Var(threshold, audio.py:1158), Var(zero_pos, audio.py:1158)], kws=(), vararg=None, varkwarg=None, target=None)" at D:\AI\ComfyUI_windows_portable\python_embeded\Lib\site-packages\librosa\core\audio.py (1174)
Prompt executed in 6.95 seconds

**Comment by if-ai** [comment]
Sorry maybe I missed some basic libs on the reqs that I assumed they would be already on the system but some people might be doing from 0 installation
try

```
pip install --upgrade numba
pip install --upgrade librosa
```

This error typically occurs when trying to use ffmpeg for audio processing, but ffmpeg is not installed or not properly configured in the system PATH. To fix this:
check you installed 

`pip install ffmpeg-python==0.2.0`

Install ffmpeg if you haven't already:

Download ffmpeg for Windows from the official website
Extract the files
Add ffmpeg's bin directory to your system's PATH environment variable

**Comment by cheezecrisp** [comment]
> Sorry maybe I missed some basic libs on the reqs that I assumed they would be already on the system but some people might be doing from 0 installation try
> 
> ```
> pip install --upgrade numba
> pip install --upgrade librosa
> ```
> 
> This error typically occurs when trying to use ffmpeg for audio processing, but ffmpeg is not installed or not properly configured in the system PATH. To fix this: check you installed
> 
> `pip install ffmpeg-python==0.2.0`
> 
> Install ffmpeg if you haven't already:
> 
> Download ffmpeg for Windows from the official website Extract the files Add ffmpeg's bin directory to your system's PATH environment variable

Thank You, it's right now.
